version: '3.0'
services:
  abci0:
    build: abci
    ports:
      - 80:80
      
  tendermint0:
    image: tendermint/tendermint:0.12.0
    volumes:
      - ./.data/cluster/mach0:/tendermint
      - tendermint0:/tendermint/data
    depends_on:
      - abci0
    ports:
      - 46656:46656
      - 46657:46657
    entrypoint:
      - tendermint
      - node
      - --p2p.seeds=tendermint1:46656
      - --consensus.create_empty_blocks=false
      - --proxy_app=abci0:46658

  abci1:
    build: abci
  tendermint1:
    image: tendermint/tendermint:0.12.0
    volumes:
      - ./.data/cluster/mach1:/tendermint
      - tendermint1:/tendermint/data
    depends_on:
      - abci1
    entrypoint:
      - tendermint
      - node
      - --p2p.seeds=tendermint2:46656
      - --consensus.create_empty_blocks=false
      - --proxy_app=abci1:46658

  abci2:
    build: abci
  tendermint2:
    image: tendermint/tendermint:0.12.0
    volumes:
      - ./.data/cluster/mach2:/tendermint
      - tendermint2:/tendermint/data
    depends_on:
      - abci2
    entrypoint:
      - tendermint
      - node
      - --p2p.seeds=tendermint3:46656
      - --consensus.create_empty_blocks=false
      - --proxy_app=abci2:46658

  abci3:
    build: abci
  tendermint3:
    image: tendermint/tendermint:0.12.0
    volumes:
      - ./.data/cluster/mach3:/tendermint
      - tendermint3:/tendermint/data
    depends_on:
      - abci3
    entrypoint:
      - tendermint
      - node
      - --p2p.seeds=tendermint4:46656
      - --consensus.create_empty_blocks=false
      - --proxy_app=abci3:46658

  abci4:
    build: abci
  tendermint4:
    image: tendermint/tendermint:0.12.0
    volumes:
      - ./.data/cluster/mach4:/tendermint
      - tendermint4:/tendermint/data
    depends_on:
      - abci4
    entrypoint:
      - tendermint
      - node
      - --p2p.seeds=tendermint0:46656
      - --consensus.create_empty_blocks=false
      - --proxy_app=anci4:46558
      
volumes:
  tendermint0:
  tendermint1:
  tendermint2:
  tendermint3:
  tendermint4: