version: '3.0'
services:
  tendermint_init:
    image: tendermint/tendermint:0.12.0
    volumes:
      - ./.data/tendermint:/tendermint
    entrypoint:
      - tendermint
      - init

  tendermint:
    image: tendermint/tendermint:0.12.0
    volumes:
      - ./.data/tendermint:/tendermint
    ports:
      - 46656:46656
      - 46657:46657
    depends_on:
      - tendermint_init
      # only needed with basecoin
      - basecoin
    entrypoint:
      - tendermint
      - node
      # only needed with basecoin
      - --proxy_app=tcp://basecoin:46658

  app:
    build: app
    environment:
      FOO: bar
    volumes:
      - ./.data/app:/app
    depends_on:
      - tendermint

  basecoin:
    image: tendermint/basecoin
    volumes:
      - ./.data/basecoin:/basecoin
    entrypoint:
      - basecoin
      - start
      - --without-tendermint
  # ethermint:
  #   image: tendermint/ethermint
  #   environment:
  #     FOO: bar
  #   volumes:
  #     ./.data/ethermint:/
  #   depends_on:
  #     - tendermint
  #     - basecoin
